# Classification of Video QoE usin Different ML Classifiers

In [1]:
import matplotlib.pyplot as plt
#plt.style.use('classic')
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import matplotlib.patheffects as mpe
import matplotlib
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics

In [2]:
df = pd.read_csv("Down_Up - Sheet2.csv")

In [3]:
def Classification(CLASS):
    if CLASS >= 0 and CLASS <= 2:
        return 'Poor'
    elif CLASS > 2 and CLASS <= 3:
        return 'Average'
    elif CLASS >3 and CLASS <= 5:
        return 'Good'

In [4]:
df['n_class']= df['P1203'].apply(Classification)

In [5]:
df.columns

Index(['ExpID', 'Case', 'Algo', 'timeslot_sec', 'timeslot_mil',
       'InterIntervalTime', 'AveragePTime', 'AveragePTime_gt100',
       'InterIntervalTime_gt100', 'TPT', 'T_pk', 'T_pk_gt100',
       'U_InterIntervalTime', 'U_AveragePTime', 'U_AveragePTime_gt100',
       'U_InterIntervalTime_gt100', 'U_TPT', 'U_T_pk', 'U_T_pk_gt100',
       '10_per_pk', '20_per_pk', '30_per_pk', '40_per_pk', '50_per_pk',
       '60_per_pk', '70_per_pk', '80_per_pk', '90_per_pk', '10IPG', '20IPG',
       '30IPG', '40IPG', '50IPG', '60IPG', '70IPG', '80IPG', '90IPG',
       'U_10_per_pk', 'U_20_per_pk', 'U_30_per_pk', 'U_40_per_pk',
       'U_50_per_pk', 'U_60_per_pk', 'U_70_per_pk', 'U_80_per_pk',
       'U_90_per_pk', 'U_10IPG', 'U_20IPG', 'U_30IPG', 'U_40IPG', 'U_50IPG',
       'U_60IPG', 'U_70IPG', 'U_80IPG', 'U_90IPG', 'Width_Height', 'P1203',
       'Clae', 'Duanmu', 'Yin', 'Yu', 'Stall', 'Bitrate', 'n_class'],
      dtype='object')

In [7]:
df['n_class']

0          Poor
1          Poor
2          Poor
3          Poor
4       Average
         ...   
997        Good
998        Good
999        Good
1000       Good
1001       Good
Name: n_class, Length: 1002, dtype: object

In [8]:
# df =df[(df['Case']=='Static-1')]

In [9]:
# df =df[(df['Case']=='Driving-2') | (df['Case']=='Driving-1')]

In [10]:
# df =df[(df['Algo']=='bba')| (df['Algo']=='elastic')| (df['Algo']=='conventional')]
# df =df[(df['Algo']=='conventional')]

In [11]:
df.shape[0]

1002

In [12]:
df['n_class'].unique()

array(['Poor', 'Average', 'Good'], dtype=object)

In [13]:
df.isnull().values.any()

False

In [14]:
nan_cols = [i for i in df.columns if df[i].isnull().any()]

In [15]:
nan_cols

[]

In [16]:
# df['Min_gt100']= df['Min_gt100'].fillna(value=df['Min_gt100'].mean())

In [17]:
# df['Max_gt100']= df['Max_gt100'].fillna(value=df['Max_gt100'].mean())

In [18]:
# df.loc[:, (df == 0).all()]


In [19]:
from sklearn import preprocessing


In [20]:
X = df[['InterIntervalTime', 'AveragePTime', 'AveragePTime_gt100',
       'InterIntervalTime_gt100', 'TPT', 'T_pk', 'T_pk_gt100',
       'U_InterIntervalTime', 'U_AveragePTime', 'U_AveragePTime_gt100',
       'U_InterIntervalTime_gt100', 'U_TPT', 'U_T_pk', 'U_T_pk_gt100',
       '10_per_pk', '20_per_pk', '30_per_pk', '40_per_pk', '50_per_pk',
       '60_per_pk', '70_per_pk', '80_per_pk', '90_per_pk',
       'U_10_per_pk', 'U_20_per_pk', 'U_30_per_pk', 'U_40_per_pk',
       'U_50_per_pk', 'U_60_per_pk', 'U_70_per_pk', 'U_80_per_pk',
       'U_90_per_pk']]
y = df['n_class']

In [21]:
X.columns

Index(['InterIntervalTime', 'AveragePTime', 'AveragePTime_gt100',
       'InterIntervalTime_gt100', 'TPT', 'T_pk', 'T_pk_gt100',
       'U_InterIntervalTime', 'U_AveragePTime', 'U_AveragePTime_gt100',
       'U_InterIntervalTime_gt100', 'U_TPT', 'U_T_pk', 'U_T_pk_gt100',
       '10_per_pk', '20_per_pk', '30_per_pk', '40_per_pk', '50_per_pk',
       '60_per_pk', '70_per_pk', '80_per_pk', '90_per_pk', 'U_10_per_pk',
       'U_20_per_pk', 'U_30_per_pk', 'U_40_per_pk', 'U_50_per_pk',
       'U_60_per_pk', 'U_70_per_pk', 'U_80_per_pk', 'U_90_per_pk'],
      dtype='object')

In [22]:
# X=preprocessing.normalize(X)
X= preprocessing.scale(X)

In [23]:
# y = df.iloc[:, 23]

In [24]:
y

0          Poor
1          Poor
2          Poor
3          Poor
4       Average
         ...   
997        Good
998        Good
999        Good
1000       Good
1001       Good
Name: n_class, Length: 1002, dtype: object

In [25]:
y.unique()

array(['Poor', 'Average', 'Good'], dtype=object)

In [26]:
X.shape[0]

1002

In [27]:
sm = SMOTE()
X, y = sm.fit_sample(X, y)

In [28]:
X.shape[0]

2484

In [29]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, stratify=y, random_state = 42)

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)

In [31]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [32]:
knn.score(X_test,y_test)

0.9504021447721179

In [33]:
y_pred = knn.predict(X_test)

In [34]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9504021447721179


In [35]:
cm=confusion_matrix(y_test,y_pred)
print('Confusion Matrix: \n', cm)
print(classification_report(y_test, y_pred))

Confusion Matrix: 
 [[237   1  10]
 [ 23 225   1]
 [  2   0 247]]
              precision    recall  f1-score   support

     Average       0.90      0.96      0.93       248
        Good       1.00      0.90      0.95       249
        Poor       0.96      0.99      0.97       249

    accuracy                           0.95       746
   macro avg       0.95      0.95      0.95       746
weighted avg       0.95      0.95      0.95       746



In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier(n_estimators=300)
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300)

In [37]:
rf_predictions = rf.predict(X_test)
accuracy_score(y_test, rf_predictions)
print('Accuracy is ' + str(round(accuracy_score(y_test, rf_predictions),2)))

Accuracy is 0.98


In [38]:
print(classification_report(y_test, rf_predictions))

              precision    recall  f1-score   support

     Average       0.98      0.97      0.97       248
        Good       1.00      0.98      0.99       249
        Poor       0.97      0.99      0.98       249

    accuracy                           0.98       746
   macro avg       0.98      0.98      0.98       746
weighted avg       0.98      0.98      0.98       746



In [39]:
cm = confusion_matrix(y_test, rf_predictions)
print('Confusion matrix\n\n', cm)

Confusion matrix

 [[241   0   7]
 [  4 245   0]
 [  2   0 247]]
